### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by Locksdsc** [qxxa/instahunt#5]
Is this supposed to claim any usernames on ig? like for example any banned usernames?

**Comment by qxxa** [comment]
Currently, the tool can only claim usernames from active accounts. So if the URL `instagram.com/[username] ` works, the username can be claimed by the script.

I've also figured out a way to check for the availability of usernames of banned accounts and other accounts. But I've not added it to the script as I've been busy.

**Comment by Locksdsc** [comment]
My proxies show failed even tho i just purchased them example : 156.228.190.106:3128
156.228.113.17:3128

**Comment by qxxa** [comment]
Can you tell me the type of proxy you're using?

**Comment by Locksdsc** [comment]
I use HTTP Proxies

**Comment by qxxa** [comment]
From my testing, I've found that HTTP proxies don't work for Instagram. I've had issues with HTTPS proxies too and only SOCKS5 seem to be working.

**Comment by Locksdsc** [comment]
Which websites do you recommend for proxies ? i bought from proxyscrape

**Comment by qxxa** [comment]
I personally use residential proxies from [Smartproxy](https://smartproxy.com/). There might be other websites with cheaper options, but I haven't tried other sites yet.

**Comment by Locksdsc** [comment]
I just bought them you think i should wait how much time for the user to be claimed?

**Comment by qxxa** [comment]
I'm not sure what type of username you're trying to claim. Can you provide me more details? 

You can dm me on instagram
